global class CommunityItemWrapper 
{
    public String title {get; set;}
	public String altTag {get; set;}
	public String commType {get; set;}
	public Boolean newItem {get; set;}
	public Decimal sortNumber {get; set;}
	public String textForBrainsharkTitle {get; set;}
	public String urlForImage {get; set;}
	public String content {get; set;}
	public String videoURL {get; set;}
	public String brainsharkURL {get; set;}
	public String videoServerURL {get; set;}
	public String videoThumbnailURL {get; set;}
	public String buttonLinkURL {get; set;}
	public String recordId {get; set;}
	public String abstractPub {get; set;}
	public String authorPub {get; set;}
	public String description {get; set;}
	public String marketingResourceURL {get; set;}
	public String ourView {get; set;}
	public String publishers {get; set;}
	public String subType {get; set;}
	public String useThisasFeturedItem {get; set;}
    public String urlForDocument {get; set;}
}